export { default as BgBanner } from './home/Main-banner-bg.jpg'
export { default as UniquenessBg } from './home/uniquenessBg.png'
export { default as ProfitabilityBg } from './home/profitability-bg.jpg'
export { default as CasesBg } from './home/casesBg.png'
export { default as TeamImage } from './home/team.png'
export { default as SpeakerImage } from './home/speaker-image.jpg'
