// PersonalHome
export { default as LogoBanner } from './home/logo.svg'
export { default as FirstCase } from './home/case-1.svg'
export { default as SecondCase } from './home/case-2.svg'

// shared
export { default as Lightning } from './shared/lightning.svg'
export { default as HeaderLogo } from './shared/HeaderLogo.svg'
export { default as UserIcon } from './shared/UserIcon.svg'
export { default as DropArrow } from './shared/DropArrow.svg'
export { default as ArrowLinkWhite } from './shared/ArrowLinkWhite.svg'
export { default as ArrowLinkPink } from './shared/ArrowLinkPink.svg'
export { default as ArrowLinkBlack } from './shared/ArrowLinkBlack.svg'
export { default as LogoBlack } from './shared/LogoBlack.svg'
export { default as MapPoint } from './shared/MapPoint.svg'
export { default as CopyIcon } from './shared/Copy.svg'
export { default as RocketIcon } from './shared/Rocket.svg'
export { default as ButtonAccordionIcon } from './shared/ButtonAccordion.svg'
export { default as LockIcon } from './shared/Lock.svg'
export { default as UnlockIcon } from './shared/Unlock.svg'
export { default as UpIcon } from './shared/UpIcon.svg'
export { default as DownIcon } from './shared/DownIcon.svg'
export { default as BigUnlockIcon } from './shared/BigUnlockIcon.svg'
export { default as BigLockIcon } from './shared/BigLockIcon.svg'
export { default as DropArrowBlackIcon } from './shared/DropArrowBlack.svg'
export { default as ArrowAccordionIcon } from './shared/ArrowAccordion.svg'
export { default as ArrowBackIcon } from './shared/ArrowBack.svg'
export { default as DoubleArrowIcon } from './shared/DoubleArrow.svg'

// personal
export { default as LogoBlue } from './personal/logoBlue.svg'
export { default as AccountIcon } from './personal/account.svg'
export { default as DashboardIcon } from './personal/dashboard.svg'
export { default as FinanceIcon } from './personal/finance.svg'
export { default as InvestmentsIcon } from './personal/investments.svg'
export { default as HelpIcon } from './personal/help.svg'
export { default as ExitIcon } from './personal/exit.svg'
export { default as VerificationIcon } from './personal/verification.svg'
export { default as PersonalCardIcon } from './personal/personalCard.svg'
export { default as PhoneIcon } from './personal/phone.svg'
export { default as SuccessIcon } from './personal/success.svg'
export { default as IndividualIcon } from './personal/individual.svg'
export { default as UsersIcon } from './personal/users.svg'
export { default as TransactionIcon } from './personal/transaction.svg'
export { default as Verification } from './personal/verificationIcon.svg'

// mock
export { default as MetaIcon } from './shared/MetaIcon.svg'
export { default as ApplyIcon } from './shared/ApplyIcon.svg'
export { default as DiagramaIcon } from './shared/DiagramaIcon.svg'
export { default as SystemIcon } from './shared/SystemIcon.svg'
